<?php
/**
 * Block Patterns
 *
 * @link https://developer.wordpress.org/reference/functions/register_block_pattern/
 * @link https://developer.wordpress.org/reference/functions/register_block_pattern_category/
 *
 * @package WordPress
 * @subpackage Alfred_Knows
 * @since Alfred Knows 1.0
 */

/**
 * Register Block Pattern Category.
 */
if ( function_exists( 'register_block_pattern_category' ) ) {

	register_block_pattern_category(
		'alfredknows',
		array( 'label' => esc_html__( 'Alfred Knows', 'alfredknows' ) )
	);
}

/**
 * Register Block Patterns.
 */
if ( function_exists( 'register_block_pattern' ) ) {

	// Tailwind Gray Line
	register_block_pattern(
		'alfredknows/tailwind-gray-line-seperator',
		array(
			'title'         => esc_html__( 'Tailwind CSS Gray Line Seperator', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="max-w-7xl mx-auto pt-12 px-4 sm:px-6 lg:pt-16 lg:px-8"><div class="py-16 px-4 mt-8 border-t border-gray-200"></div></div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// 1 Call to Action.
	register_block_pattern(
		'alfredknows/new-1-call-to-action',
		array(
			'title'         => esc_html__( 'Tailwind CSS New Page Hero Section - 1 Call to Action', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="max-w-7xl mx-auto pt-12 px-4 sm:px-6 lg:pt-16 lg:px-8 text-center lg:text-left tailwind-css-content-block">',
					'<div class="flex items-center flex-wrap space-y-10">',
					'<div class="flex-1">',
					'<h1 class="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl lg:text-5xl xl:text-6xl">',
					'<span>Email verification plus&nbsp;<span class="text-rose-100">threat detection.</span></span>',
					'</h1>',
					'<p class="mt-3 max-w-md mx-auto text-lg text-gray-500 sm:text-xl md:mt-5 md:max-w-3xl">250 Free Credits + Free List Evaluations</p>',
					'<div class="mt-10 sm:flex sm:justify-center lg:justify-start">',
					'<div class="rounded-md shadow">',
					'<a class="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-rose-100 hover:bg-rose-200 md:py-4 md:text-lg md:px-10" href="https://my.alfredknows.com/register">Start Here</a>',
					'</div>',
					'</div>',
					'</div>',
					'<div>',
					'<img loading="lazy" class="alignnone wp-image-570 size-full" src="https://alfredknows.com/wp-content/uploads/2021/07/email-list-cleaner-2.png" alt="Email List Cleaner" width="600" height="489">',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Sub-Page Hero Call to Action.
	register_block_pattern(
		'alfredknows/sub-page-hero-call-to-action',
		array(
			'title'         => esc_html__( 'Tailwind CSS Sub-Page Hero Section - 1 Call to Action', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="max-w-7xl mx-auto pt-12 px-4 sm:px-6 lg:pt-16 lg:px-8 text-center lg:text-left tailwind-css-content-block">',
					'<div class="flex items-center flex-wrap space-y-10">',
					'<div class="flex-1">',
					'<h1 class="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl lg:text-5xl xl:text-6xl">',
					'<span>Email verification plus&nbsp;<span class="text-rose-100">threat detection.</span></span>',
					'</h1>',
					'<p class="mt-3 max-w-md mx-auto text-lg text-gray-500 sm:text-xl md:mt-5 md:max-w-3xl">250 Free Credits + Free List Evaluations</p>',
					'<div class="mt-10 sm:flex sm:justify-center lg:justify-start">',
					'<div class="rounded-md shadow">',
					'<a class="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-rose-100 hover:bg-rose-200 md:py-4 md:text-lg md:px-10" href="https://my.alfredknows.com/register">Start Here</a>',
					'</div>',
					'</div>',
					'</div>',
					'<div>',
					'<img loading="lazy" class="alignnone wp-image-737" src="https://alfredknows.com/wp-content/uploads/2021/07/email-hygiene-service.png" alt="Email Hygiene Service" width="539" height="525">',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Sub-Page Hero No Call to Action.
	register_block_pattern(
		'alfredknows/sub-page-hero-no-call-to-action',
		array(
			'title'         => esc_html__( 'Tailwind CSS Sub-Page Hero Section - NO Call to Action', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="max-w-7xl mx-auto pt-12 px-4 sm:px-6 lg:pt-16 lg:px-8 text-center lg:text-left tailwind-css-content-block">',
					'<div class="flex items-center flex-wrap space-y-10">',
					'<div class="flex-1">',
					'<h1 class="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl lg:text-5xl xl:text-6xl">',
					'<span>Email verification plus&nbsp;<span class="text-rose-100">threat detection.</span></span>',
					'</h1>',
					'<p class="mt-3 max-w-md mx-auto text-lg text-gray-500 sm:text-xl md:mt-5 md:max-w-3xl">250 Free Credits + Free List Evaluations</p>',
					'</div>',
					'<div>',
					'<img loading="lazy" class="alignnone wp-image-737" src="https://alfredknows.com/wp-content/uploads/2021/07/email-hygiene-service.png" alt="Email Hygiene Service" width="539" height="525">',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Logo Grid 1x4
	register_block_pattern(
		'alfredknows/logo-grid-1x4',
		array(
			'title'         => esc_html__( 'Tailwind CSS Logo Grid 1x4', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="mt-24 sm:mt-32 lg:mt-24 bg-gray-50 tailwind-css-content-block">',
					'<div class="max-w-7xl mx-auto pt-20 pb-8 px-4 sm:px-6 lg:px-8">',
					'<h2 class="text-center text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">Trusted by over 5 very average small businesses</h2>',
					'<div class="mt-6 grid grid-cols-2 gap-0.5 md:grid-cols-4 lg:mt-8">',
					'<div class="col-span-1 flex justify-center align-middle py-5 px-8 flex-wrap">',
					'<div class="grid grid-rows-2">',
					'<div class="row-span-1">',
					'<img  src="https://alfredknows.com/wp-content/uploads/2021/06/mailchimp-logo-sm.png" alt="Workcation">',
					'</div>',
					'<div class="mt-2 row-span-1 text-center text-xs">Customer Since 2010</div>',
					'</div>',
					'</div>',
					'<div class="col-span-1 flex justify-center align-middle py-5 px-8 flex-wrap">',
					'<div class="grid grid-rows-2">',
					'<div class="row-span-1">',
					'<img  src="https://alfredknows.com/wp-content/uploads/2021/06/oracle-marketing-cloud-logo-sm.png" alt="Workcation">',
					'</div>',
					'<div class="mt-2 row-span-1 text-center text-xs">Customer Since 2010</div>',
					'</div>',
					'</div>',
					'<div class="col-span-1 flex justify-center align-middle py-5 px-8 flex-wrap">',
					'<div class="grid grid-rows-2">',
					'<div class="row-span-1">',
					'<img src="https://alfredknows.com/wp-content/uploads/2021/06/klaviyo-logo-sm.png" alt="Workcation">',
					'</div>',
					'<div class="mt-2 row-span-1 text-center text-xs">Customer Since 2010</div>',
					'</div>',
					'</div>',
					'<div class="col-span-1 flex justify-center align-middle py-5 px-8 flex-wrap">',
					'<div class="grid grid-rows-2">',
					'<div class="row-span-1">',
					'<img src="https://tailwindui.com/img/logos/transistor-logo-gray-400.svg" alt="Workcation">',
					'</div>',
					'<div class="mt-2 row-span-1 text-center text-xs">Customer Since 2010</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Pictures Grid 1x3
	register_block_pattern(
		'alfredknows/pictures-grid-1x3',
		array(
			'title'         => esc_html__( 'Tailwind CSS Pictures Grid 1x3', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="bg-white tailwind-css-content-block">',
					'<div class="max-w-7xl mx-auto py-12 px-4 text-center sm:px-6 lg:px-8">',
					'<div class="space-y-12">',
					'<div class="space-y-5 sm:mx-auto sm:max-w-xl sm:space-y-4 lg:max-w-7xl">',
					'<h2 class="text-center text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">' . esc_html__( 'Know at a glance' ) . '</h2>',
					'</div>',
					'<div class="mx-auto space-y-24 sm:grid sm:grid-cols-2 sm:gap-16 sm:space-y-0 lg:grid-cols-3 lg:max-w-7xl">',
					'<div>',
					'<div class="space-y-6">',
					'<img class="mx-auto" src="https://images.unsplash.com/photo-1517365830460-955ce3ccd263?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=1024&h=1024&q=80" alt="" />',
					'<div class="space-y-2">',
					'<div class="text-lg leading-6 space-y-1">',
					'<div class="text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Bad' ) . '</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<div>',
					'<div class="space-y-6">',
					'<img class="mx-auto" src="https://images.unsplash.com/photo-1517365830460-955ce3ccd263?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=1024&h=1024&q=80" alt="" />',
					'<div class="space-y-2">',
					'<div class="text-lg leading-6 space-y-1">',
					'<div class="text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Poor' ) . '</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<div>',
					'<div class="space-y-6">',
					'<img class="mx-auto" src="https://images.unsplash.com/photo-1517365830460-955ce3ccd263?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=1024&h=1024&q=80" alt="" />',
					'<div class="space-y-2">',
					'<div class="text-lg leading-6 space-y-1">',
					'<div class="text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Risky' ) . '</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<div class="mx-auto">' . esc_html__( 'Our results are as easy to understand as they are accurate. ' ) . '<a href="#put-link-here">' . esc_html__( 'Learn more' ) . '</a></div>',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Pictures Grid 1x3 Extra Text
	register_block_pattern(
		'alfredknows/pictures-grid-1x3-extras',
		array(
			'title'         => esc_html__( 'Tailwind CSS Pictures Grid 1x3 + Extra Text', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="bg-white tailwind-css-content-block">',
					'<div class="max-w-7xl mx-auto py-12 px-4 text-center sm:px-6 lg:px-8">',
					'<div class="space-y-12">',
					'<div class="space-y-5 sm:mx-auto sm:max-w-xl sm:space-y-4 lg:max-w-7xl">',
					'<h2 class="text-center text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">' . esc_html__( 'Know at a glance' ) . '</h2>',
					'<div class="mt-4 text-lg text-gray-500">' . esc_html__( 'Extra text for under the headline text.' ) . '</div>',
					'</div>',
					'<div class="mx-auto space-y-24 sm:grid sm:grid-cols-2 sm:gap-16 sm:space-y-0 lg:grid-cols-3 lg:max-w-7xl">',
					'<div>',
					'<div class="space-y-6">',
					'<img class="mx-auto" src="https://images.unsplash.com/photo-1517365830460-955ce3ccd263?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=1024&h=1024&q=80" alt="" />',
					'<div class="space-y-2">',
					'<div class="text-lg leading-6 space-y-1">',
					'<div class="text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Bad' ) . '</div>',
					'<div class="mt-2 text-base text-gray-500">' . esc_html__( 'Extra text block under the image.' ) . '</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<div>',
					'<div class="space-y-6">',
					'<img class="mx-auto" src="https://images.unsplash.com/photo-1517365830460-955ce3ccd263?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=1024&h=1024&q=80" alt="" />',
					'<div class="space-y-2">',
					'<div class="text-lg leading-6 space-y-1">',
					'<div class="text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Poor' ) . '</div>',
					'<div class="mt-2 text-base text-gray-500">' . esc_html__( 'Extra text block under the image.' ) . '</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<div>',
					'<div class="space-y-6">',
					'<img class="mx-auto" src="https://images.unsplash.com/photo-1517365830460-955ce3ccd263?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=1024&h=1024&q=80" alt="" />',
					'<div class="space-y-2">',
					'<div class="text-lg leading-6 space-y-1">',
					'<div class="text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Risky' ) . '</div>',
					'<div class="mt-2 text-base text-gray-500">' . esc_html__( 'Extra text block under the image.' ) . '</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<div class="mx-auto">' . esc_html__( 'Our results are as easy to understand as they are accurate. ' ) . '<a href="#put-link-here">' . esc_html__( 'Learn more' ) . '</a></div>',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Features Grid 2x3
	register_block_pattern(
		'alfredknows/features-grid-2x3',
		array(
			'title'         => esc_html__( 'Tailwind CSS Features Grid 2x3', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="relative bg-white py-12 tailwind-css-content-block">',
					'<div class="mx-auto max-w-md px-4 text-center sm:max-w-3xl sm:px-6 lg:px-8 lg:max-w-7xl">',
					'<h2 class="text-center text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">',
					'<span class="block text-base font-semibold tracking-wider text-rose-100 uppercase">' . esc_html__( 'Deploy faster' ) . '</span>',
					'<span class="block mt-2 text-3xl font-extrabold text-gray-900 tracking-tight sm:text-4xl">' . esc_html__( 'Everything you need to deploy your app' ) . '</span>',
					'</h2>',
					'<p class="mt-5 max-w-prose mx-auto text-xl text-gray-500">' . esc_html__( 'Phasellus lorem quam molestie id quisque diam aenean nulla in. Accumsan in quis quis nunc, ullamcorper malesuada. Eleifend condimentum id viverra nulla.' ) . '</p>',
					'<div class="mt-12">',
					'<div class="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">',
					'<div class="pt-6">',
					'<div class="flow-root bg-gray-50 rounded-lg px-6 pb-8">',
					'<div class="-mt-6">',
					'<div>',
					'<span class="inline-flex items-center justify-center p-3 bg-rose-100 rounded-md shadow-lg">',
					'<span class="material-icons md-24 md-light">cloud_upload</span>',
					'</span>',
					'</div>',
					'<h3 class="mt-8 text-lg font-medium text-gray-900 tracking-tight">Push to Deploy</h3>',
					'<p class="mt-5 text-base text-gray-500">' . esc_html__( 'Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.' ) . '</p>',
					'</div>',
					'</div>',
					'</div>',
					'<div class="pt-6">',
					'<div class="flow-root bg-gray-50 rounded-lg px-6 pb-8">',
					'<div class="-mt-6">',
					'<div>',
					'<span class="inline-flex items-center justify-center p-3 bg-rose-100 rounded-md shadow-lg">',
					'<span class="material-icons md-24 md-light">lock</span>',
					'</span>',
					'</div>',
					'<h3 class="mt-8 text-lg font-medium text-gray-900 tracking-tight">SSL Certificates</h3>',
					'<p class="mt-5 text-base text-gray-500">' . esc_html__( 'Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.' ) . '</p>',
					'</div>',
					'</div>',
					'</div>',
					'<div class="pt-6">',
					'<div class="flow-root bg-gray-50 rounded-lg px-6 pb-8">',
					'<div class="-mt-6">',
					'<div>',
					'<span class="inline-flex items-center justify-center p-3 bg-rose-100 rounded-md shadow-lg">',
					'<span class="material-icons md-24 md-light">cached</span>',
					'</span>',
					'</div>',
					'<h3 class="mt-8 text-lg font-medium text-gray-900 tracking-tight">Simple Queues</h3>',
					'<p class="mt-5 text-base text-gray-500">' . esc_html__( 'Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.' ) . '</p>',
					'</div>',
					'</div>',
					'</div>',
					'<div class="pt-6">',
					'<div class="flow-root bg-gray-50 rounded-lg px-6 pb-8">',
					'<div class="-mt-6">',
					'<div>',
					'<span class="inline-flex items-center justify-center p-3 bg-rose-100 rounded-md shadow-lg">',
					'<span class="material-icons md-24 md-light">verified_user</span>',
					'</span>',
					'</div>',
					'<h3 class="mt-8 text-lg font-medium text-gray-900 tracking-tight">Advanced Security</h3>',
					'<p class="mt-5 text-base text-gray-500">' . esc_html__( 'Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.' ) . '</p>',
					'</div>',
					'</div>',
					'</div>',
					'<div class="pt-6">',
					'<div class="flow-root bg-gray-50 rounded-lg px-6 pb-8">',
					'<div class="-mt-6">',
					'<div>',
					'<span class="inline-flex items-center justify-center p-3 bg-rose-100 rounded-md shadow-lg">',
					'<span class="material-icons md-24 md-light">settings</span>',
					'</span>',
					'</div>',
					'<h3 class="mt-8 text-lg font-medium text-gray-900 tracking-tight">Powerful API</h3>',
					'<p class="mt-5 text-base text-gray-500">' . esc_html__( 'Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.' ) . '</p>',
					'</div>',
					'</div>',
					'</div>',
					'<div class="pt-6">',
					'<div class="flow-root bg-gray-50 rounded-lg px-6 pb-8">',
					'<div class="-mt-6">',
					'<div>',
					'<span class="inline-flex items-center justify-center p-3 bg-rose-100 rounded-md shadow-lg">',
					'<span class="material-icons md-24 md-light">storage</span>',
					'</span>',
					'</div>',
					'<h3 class="mt-8 text-lg font-medium text-gray-900 tracking-tight">Database Backups</h3>',
					'<p class="mt-5 text-base text-gray-500">' . esc_html__( 'Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.' ) . '</p>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Features Grid 1x3
	register_block_pattern(
		'alfredknows/features-grid-1x3',
		array(
			'title'         => esc_html__( 'Tailwind CSS Features Grid 1x3', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="relative bg-white py-12 tailwind-css-content-block">',
					'<div class="mx-auto max-w-md px-4 text-center sm:max-w-3xl sm:px-6 lg:px-8 lg:max-w-7xl">',
					'<h2 class="text-center text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">',
					'<span class="block text-base font-semibold tracking-wider text-rose-100 uppercase">' . esc_html__( 'Deploy faster' ) . '</span>',
					'<span class="block mt-2 text-3xl font-extrabold text-gray-900 tracking-tight sm:text-4xl">' . esc_html__( 'Everything you need to deploy your app' ) . '</span>',
					'</h2>',
					'<p class="mt-5 max-w-prose mx-auto text-xl text-gray-500">' . esc_html__( 'Phasellus lorem quam molestie id quisque diam aenean nulla in. Accumsan in quis quis nunc, ullamcorper malesuada. Eleifend condimentum id viverra nulla.' ) . '</p>',
					'<div class="mt-12">',
					'<div class="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">',
					'<div class="pt-6">',
					'<div class="flow-root bg-gray-50 rounded-lg px-6 pb-8">',
					'<div class="-mt-6">',
					'<div>',
					'<span class="inline-flex items-center justify-center p-3 bg-rose-100 rounded-md shadow-lg">',
					'<span class="material-icons md-24 md-light">cloud_upload</span>',
					'</span>',
					'</div>',
					'<h3 class="mt-8 text-lg font-medium text-gray-900 tracking-tight">Push to Deploy</h3>',
					'<p class="mt-5 text-base text-gray-500">' . esc_html__( 'Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.' ) . '</p>',
					'</div>',
					'</div>',
					'</div>',
					'<div class="pt-6">',
					'<div class="flow-root bg-gray-50 rounded-lg px-6 pb-8">',
					'<div class="-mt-6">',
					'<div>',
					'<span class="inline-flex items-center justify-center p-3 bg-rose-100 rounded-md shadow-lg">',
					'<span class="material-icons md-24 md-light">lock</span>',
					'</span>',
					'</div>',
					'<h3 class="mt-8 text-lg font-medium text-gray-900 tracking-tight">SSL Certificates</h3>',
					'<p class="mt-5 text-base text-gray-500">' . esc_html__( 'Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.' ) . '</p>',
					'</div>',
					'</div>',
					'</div>',
					'<div class="pt-6">',
					'<div class="flow-root bg-gray-50 rounded-lg px-6 pb-8">',
					'<div class="-mt-6">',
					'<div>',
					'<span class="inline-flex items-center justify-center p-3 bg-rose-100 rounded-md shadow-lg">',
					'<span class="material-icons md-24 md-light">cached</span>',
					'</span>',
					'</div>',
					'<h3 class="mt-8 text-lg font-medium text-gray-900 tracking-tight">Simple Queues</h3>',
					'<p class="mt-5 text-base text-gray-500">' . esc_html__( 'Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.' ) . '</p>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Testimonials 1x2
	register_block_pattern(
		'alfredknows/testimonials',
		array(
			'title'         => esc_html__( 'Tailwind CSS Testimonials Grid 1x2', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="bg-rose-50 my-12 tailwind-css-content-block">',
					'<div class="max-w-7xl mx-auto md:grid md:grid-cols-2 md:px-6 lg:px-8">',
					'<div class="py-12 px-4 sm:px-6 md:flex md:flex-col md:py-16 md:pl-0 md:pr-10 lg:pr-16">',
					'<div class="md:flex-shrink-0">',
					'<img class="h-12" src="https://tailwindui.com/img/logos/tuple-logo-indigo-300.svg" alt="Tuple" />',
					'</div>',
					'<div class="mt-6 md:flex-grow md:flex md:flex-col">',
					'<div class="relative text-lg font-medium text-gray-900 md:flex-grow">',
					'<div class="material-icons md-48 absolute top-0 left-0 transform -translate-x-2 -translate-y-4 h-48 w-48 text-rose-100">format_quote</div>',
					'<div class="relative">      Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo expedita voluptas culpa sapiente alias molestiae. Numquam corrupti in laborum sed rerum et corporis.</div>',
					'</div>',
					'<div class="mt-8">',
					'<div class="flex items-start">',
					'<div class="ml-4">',
					'<div class="text-base font-medium text-gray-900">Judith Black</div>',
					'<div class="text-base font-medium text-gray-900">CEO, Tuple</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<div class="py-12 px-4 sm:px-6 md:py-16 md:pr-0 md:pl-10 lg:pl-16">',
					'<div class="md:flex-shrink-0">',
					'<img class="h-12" src="https://tailwindui.com/img/logos/workcation-logo-indigo-300.svg" alt="Workcation" />',
					'</div>',
					'<div class="mt-6 md:flex-grow md:flex md:flex-col">',
					'<div class="relative text-lg font-medium text-gray-900 md:flex-grow">',
					'<div class="material-icons md-48 absolute top-0 left-0 transform -translate-x-2 -translate-y-4 h-48 w-48 text-rose-100">format_quote</div>',
					'<div class="relative">      Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo expedita voluptas culpa sapiente alias molestiae. Numquam corrupti in laborum sed rerum et corporis. Nemo expedita voluptas culpa sapiente alias molestiae.</div>',
					'</div>',
					'<div class="mt-8">',
					'<div class="flex items-start">',
					'<div class="ml-4">',
					'<div class="text-base font-medium text-gray-900">Joseph Rodriguez</div>',
					'<div class="text-base font-medium text-gray-900">CEO, Workcation</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// 3 Column Cards
	register_block_pattern(
		'alfredknows/3-column-cards',
		array(
			'title'         => esc_html__( 'Tailwind CSS 3 Column Cards', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="relative bg-gray-50 py-12 pb-20 px-4 sm:px-6 lg:pb-28 lg:px-8 tailwind-css-content-block">',
					'<div class="absolute inset-0">',
					'<div class="bg-white h-1/3 sm:h-2/3"></div>',
					'</div>',
					'<div class="relative max-w-7xl mx-auto">',
					'<div class="text-center">',
					'<h2 class="text-center text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">' . esc_html__( 'From the blog' ) . '</h2>',
					'<p class="mt-3 max-w-2xl mx-auto text-xl text-gray-500 sm:mt-4">' . esc_html__( 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsa libero labore natus atque, ducimus sed.' ) . '</p>',
					'</div>',
					'<div class="mt-12 max-w-lg mx-auto grid gap-5 lg:grid-cols-3 lg:max-w-none">',
					'<div class="flex flex-col rounded-lg shadow-lg overflow-hidden">',
					'<div class="flex-shrink-0">',
					'<img class="h-48 w-full object-cover" src="https://images.unsplash.com/photo-1496128858413-b36217c2ce36?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1679&q=80" alt="">',
					'</div>',
					'<div class="flex-1 bg-white p-6 flex flex-col justify-between">',
					'<div class="flex-1">',
					'<p class="text-sm font-medium text-indigo-600">',
					'<a href="#" class="hover:underline">' . esc_html__( 'Article' ) . '</a>',
					'</p>',
					'<a href="#" class="block mt-2">',
					'<p class="text-xl font-semibold text-gray-900">' . esc_html__( 'Boost your conversion rate' ) . '</p>',
					'<p class="mt-3 text-base text-gray-500">' . esc_html__( 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto accusantium praesentium eius, ut atque fuga culpa, similique sequi cum eos quis dolorum.' ) . '</p>',
					'</a>',
					'</div>',
					'<div class="mt-6 flex items-center">',
					'<div class="flex-shrink-0">',
					'<a href="#">',
					'<span class="sr-only">' . esc_html__( 'Roel Aufderehar' ) . '</span>',
					'<img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">',
					'</a>',
					'</div>',
					'<div class="ml-3">',
					'<p class="text-sm font-medium text-gray-900">',
					'<a href="#" class="hover:underline">' . esc_html__( 'Roel Aufderehar' ) . '</a>',
					'</p>',
					'<div class="flex space-x-1 text-sm text-gray-500">',
					'<time datetime="2020-03-16">' . esc_html__( 'Mar 16, 2020' ) . '</time>',
					'<span aria-hidden="true">&middot;</span>',
					'<span>' . esc_html__( '6 min read' ) . '</span>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<div class="flex flex-col rounded-lg shadow-lg overflow-hidden">',
					'<div class="flex-shrink-0">',
					'<img class="h-48 w-full object-cover" src="https://images.unsplash.com/photo-1547586696-ea22b4d4235d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1679&q=80" alt="">',
					'</div>',
					'<div class="flex-1 bg-white p-6 flex flex-col justify-between">',
					'<div class="flex-1">',
					'<p class="text-sm font-medium text-indigo-600">',
					'<a href="#" class="hover:underline">' . esc_html__( 'Video' ) . '</a>',
					'</p>',
					'<a href="#" class="block mt-2">',
					'<p class="text-xl font-semibold text-gray-900">' . esc_html__( 'How to use search engine optimization to drive sales' ) . '</p>',
					'<p class="mt-3 text-base text-gray-500">' . esc_html__( 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit facilis asperiores porro quaerat doloribus, eveniet dolore. Adipisci tempora aut inventore optio animi., tempore temporibus quo laudantium.' ) . '</p>',
					'</a>',
					'</div>',
					'<div class="mt-6 flex items-center">',
					'<div class="flex-shrink-0">',
					'<a href="#">',
					'<span class="sr-only">' . esc_html__( 'Brenna Goyette' ) . '</span>',
					'<img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">',
					'</a>',
					'</div>',
					'<div class="ml-3">',
					'<p class="text-sm font-medium text-gray-900">',
					'<a href="#" class="hover:underline">' . esc_html__( 'Brenna Goyette' ) . '</a>',
					'</p>',
					'<div class="flex space-x-1 text-sm text-gray-500">',
					'<time datetime="2020-03-10">' . esc_html__( 'Mar 10, 2020' ) . '</time>',
					'<span aria-hidden="true">&middot;</span>',
					'<span>' . esc_html__( '4 min read' ) . '</span>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<div class="flex flex-col rounded-lg shadow-lg overflow-hidden">',
					'<div class="flex-shrink-0">',
					'<img class="h-48 w-full object-cover" src="https://images.unsplash.com/photo-1492724441997-5dc865305da7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1679&q=80" alt="">',
					'</div>',
					'<div class="flex-1 bg-white p-6 flex flex-col justify-between">',
					'<div class="flex-1">',
					'<p class="text-sm font-medium text-indigo-600">',
					'<a href="#" class="hover:underline">' . esc_html__( 'Case Study' ) . '</a>',
					'</p>',
					'<a href="#" class="block mt-2">',
					'<p class="text-xl font-semibold text-gray-900">' . esc_html__( 'Improve your customer experience' ) . '</p>',
					'<p class="mt-3 text-base text-gray-500">' . esc_html__( 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint harum rerum voluptatem quo recusandae magni placeat saepe molestiae, sed excepturi cumque corporis perferendis hic.' ) . '</p>',
					'</a>',
					'</div>',
					'<div class="mt-6 flex items-center">',
					'<div class="flex-shrink-0">',
					'<a href="#">',
					'<span class="sr-only">' . esc_html__( 'Daniela Metz' ) . '</span>',
					'<img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">',
					'</a>',
					'</div>',
					'<div class="ml-3">',
					'<p class="text-sm font-medium text-gray-900">',
					'<a href="#" class="hover:underline">' . esc_html__( 'Daniela Metz' ) . '</a>',
					'</p>',
					'<div class="flex space-x-1 text-sm text-gray-500">',
					'<time datetime="2020-02-12">' . esc_html__( 'Feb 12, 2020' ) . '</time>',
					'<span aria-hidden="true">&middot;</span>',
					'<span>' . esc_html__( '11 min read' ) . '</span>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Tailwind CSS Call to Action - Colored
	register_block_pattern(
		'alfredknows/call-to-action-colored',
		array(
			'title'         => esc_html__( 'Tailwind CSS Call to Action - Colored', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="bg-rose-100 tailwind-css-content-block">',
					'<div class="max-w-2xl mx-auto text-center py-12 px-4 sm:px-6 lg:px-8">',
					'<h2 class="text-center text-3xl leading-8 font-extrabold tracking-tight text-white sm:text-4xl">',
					'<span class="block">' . esc_html__( 'Boost your productivity.' ) . '</span>',
					'<span class="block">' . esc_html__( 'Start using Workflow today.' ) . '</span>',
					'</h2>',
					'<p class="mt-4 text-lg leading-6 text-gray-900">' . esc_html__( 'Ac euismod vel sit maecenas id pellentesque eu sed consectetur. Malesuada adipiscing sagittis vel nulla nec.' ) . '</p>',
					'<a href="#" class="mt-8 w-full inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-rose-100 bg-white hover:bg-gray-50 sm:w-auto">' . esc_html__( 'Sign up for free' ) . '</a>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Tailwind CSS Call to Action - Colored w/ Screenshot
	register_block_pattern(
		'alfredknows/call-to-action-colored-screenshot',
		array(
			'title'         => esc_html__( 'Tailwind CSS Call to Action - Colored w/ Screenshot', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="bg-white">',
					'<div class="mx-auto py-12">',
					'<div class="bg-rose-100 overflow-hidden lg:grid lg:grid-cols-2 lg:gap-4">',
					'<div class="pt-10 pb-12 px-6 sm:pt-16 sm:px-16 lg:py-16 lg:pr-0 xl:py-20 xl:px-20">',
					'<div class="lg:self-center">',
					'<h2 class="text-3xl font-extrabold text-white sm:text-4xl">',
					'<span class="block">' . esc_html__( 'Ready to dive in?' ) . '</span>',
					'</h2>',
					'<p class="mt-4 text-lg leading-6 text-gray-900">' . esc_html__( 'Ac euismod vel sit maecenas id pellentesque eu sed consectetur. Malesuada adipiscing sagittis vel nulla nec.' ) . '</p>',
					'<a href="#" class="mt-8 bg-white border border-transparent rounded-md shadow px-5 py-3 inline-flex items-center text-base font-medium text-rose-100 hover:bg-gray-50">' . esc_html__( 'Start here' ) . '</a>',
					'</div>',
					'</div>',
					'<div class="-mt-6 aspect-w-5 aspect-h-3 md:aspect-w-2 md:aspect-h-1">',
					'<img class="transform translate-x-6 translate-y-6 rounded-md object-cover object-left-top sm:translate-x-16 lg:translate-y-20" src="https://tailwindui.com/img/component-images/full-width-with-sidebar.jpg" alt="App screenshot">',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Tailwind CSS Call to Action - Colored w/ Screenshot & Pricing Tool
	register_block_pattern(
		'alfredknows/call-to-action-colored-screenshot-price-tool',
		array(
			'title'         => esc_html__( 'Tailwind CSS Call to Action - Colored w/ Screenshot & Pricing Tool', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="tailwind-css-content-block">',
					'<div class="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8 text-center">',
					'<h2 class="text-3xl font-extrabold text-white sm:text-4xl">' . esc_html__( 'How many emails to you have?' ) . '</h2>',
					'<div class="overflow-hidden lg:grid lg:grid-cols-2 lg:gap-4">',
					'<div class="my-5">',
					'<table class="min-w-full divide-y divide-gray-500 border border-gray-500">',
					'<thead class="bg-gray-50">',
					'<tr>',
					'<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">' . esc_html__( 'QUANTITY RANGE' ) . '</th>',
					'<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">' . esc_html__( 'COST PER 1 EMAIL' ) . '</th>',
					'</tr>',
					'</thead>',
					'<tbody>',
					'<tr class="bg-white">',
					'<td class="px-6 py-4 whitespace-nowrap text-sm text-left font-medium text-gray-900">' . esc_html__( '1 - 2,500' ) . '</td>',
					'<td class="px-6 py-4 whitespace-nowrap text-sm text-left text-gray-500">' . esc_html__( '$0.01' ) . '</td>',
					'</tr>',
					'<tr class="bg-gray-50">',
					'<td class="px-6 py-4 whitespace-nowrap text-sm text-left font-medium text-gray-900">' . esc_html__( '2,501 - 100,000' ) . '</td>',
					'<td class="px-6 py-4 whitespace-nowrap text-sm text-left text-gray-500">' . esc_html__( '$0.008' ) . '</td>',
					'</tr>',
					'<tr class="bg-white">',
					'<td class="px-6 py-4 whitespace-nowrap text-sm text-left font-medium text-gray-900">' . esc_html__( '100,001 - 250,000' ) . '</td>',
					'<td class="px-6 py-4 whitespace-nowrap text-sm text-left text-gray-500">' . esc_html__( '$0.006' ) . '</td>',
					'</tr>',
					'<tr class="bg-gray-50">',
					'<td class="px-6 py-4 whitespace-nowrap text-sm text-left font-medium text-gray-900">' . esc_html__( '250,001 - 500,000' ) . '</td>',
					'<td class="px-6 py-4 whitespace-nowrap text-sm text-left text-gray-500">' . esc_html__( '$0.005' ) . '</td>',
					'</tr>',
					'<tr class="bg-white">',
					'<td class="px-6 py-4 whitespace-nowrap text-sm text-left font-medium text-gray-900">' . esc_html__( '500,001 - 1,000,000' ) . '</td>',
					'<td class="px-6 py-4 whitespace-nowrap text-sm text-left text-gray-500">' . esc_html__( '$0.004' ) . '</td>',
					'</tr>',
					'<tr class="bg-gray-50">',
					'<td class="px-6 py-4 whitespace-nowrap text-sm text-left font-medium text-gray-900">' . esc_html__( '1,000,000 or more' ) . '</td>',
					'<td class="px-6 py-4 whitespace-nowrap text-sm text-left text-gray-500">' . esc_html__( 'Contact Us' ) . '</td>',
					'</tr>',
					'</tbody>',
					'</table>',
					'</div>',
					'<div class="pt-10 pb-12 px-6 sm:pt-16 sm:px-16 lg:py-16 lg:pr-0 xl:py-20 xl:px-20">',
					'<div class="lg:self-center">',
					'<div id="alfredKnowsPriceRangerTool" class="p-5">',
					'<input id="totalNumEmails" type="text" class="text-xl bg-white mx-auto w-32 h-16 my-5 text-center flex items-center justify-center" />',
					'<input type="range" min="1" max="1000000" value="5000" id="emailListPriceSlide" />',
					'<div id="totalListPrice" class="text-xl bg-white mx-auto w-32 h-16 my-5 text-center flex items-center justify-center"></div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<a href="#" class="mt-8 bg-rose-100 border border-transparent rounded-md shadow px-5 py-3 inline-flex items-center text-base font-medium text-white hover:bg-rose-200">' . esc_html__( 'Start Free' ) . '</a>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Tailwind CSS Call to Action - Grey w/ Screenshot
	register_block_pattern(
		'alfredknows/call-to-action-grey-screenshot',
		array(
			'title'         => esc_html__( 'Tailwind CSS Call to Action - Grey w/ Screenshot', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="py-12 bg-gray-50 overflow-hidden tailwind-css-content-block">',
					'<div class="relative max-w-xl mx-auto px-4 sm:px-6 lg:px-8 lg:max-w-7xl">',
					'<div class="relative lg:grid lg:grid-cols-2 lg:gap-8 justify-start">',
					'<div class="relative">',
					'<h2 class="text-2xl font-extrabold text-gray-900 tracking-tight sm:text-3xl">' . esc_html__( 'Transfer funds world-wide' ) . '</h2>',
					'<p class="mt-3 text-lg text-gray-500">' . esc_html__( 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur minima sequi recusandae, porro maiores officia assumenda aliquam laborum ab aliquid veritatis impedit odit adipisci optio iste blanditiis facere. Totam, velit.' ) . '</p>',
					'</div>',
					'<div class="mt-10 -mx-4 relative lg:mt-0" aria-hidden="true">',
					'<img class="relative mx-auto" width="490" src="https://tailwindui.com/img/features/feature-example-1.png" alt="">',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Tailwind CSS Product Hero
	register_block_pattern(
		'alfredknows/product-hero',
		array(
			'title'         => esc_html__( 'Tailwind CSS Product Hero', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="relative bg-rose-100 my-12 tailwind-css-content-block">',
					'<div class="absolute inset-0">',
					'<img class="w-full h-full object-cover" src="https://images.unsplash.com/photo-1525130413817-d45c1d127c42?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1920&q=60&&sat=-100" alt="">',
					'<div class="absolute inset-0 bg-rose-100 mix-blend-multiply" aria-hidden="true"></div>',
					'</div>',
					'<div class="relative max-w-7xl mx-auto py-24 px-4 sm:py-32 sm:px-6 lg:px-8">',
					'<h2 class="text-center text-3xl leading-8 font-extrabold tracking-tight text-white sm:text-4xl">' . esc_html__( 'Get in touch' ) . '</h2>',
					'<p class="mt-6 text-xl text-white max-w-3xl">' . esc_html__( 'Mattis amet hendrerit dolor, quisque lorem pharetra. Pellentesque lacus nisi urna, arcu sociis eu. Orci vel lectus nisl eget eget ut consectetur. Sit justo viverra non adipisicing elit distinctio.' ) . '</p>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Tailwind CSS Features List - 8 Items
	register_block_pattern(
		'alfredknows/features-list-8',
		array(
			'title'         => esc_html__( 'Tailwind CSS Features List - 8 Items', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="bg-white tailwind-css-content-block">',
					'<div class="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8 lg:grid lg:grid-cols-3 lg:gap-x-8">',
					'<div>',
					'<h2 class="text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl m-0">',
					'<span class="block text-3xl font-extrabold text-gray-900">' . esc_html__( 'All-in-one platform' ) . '</span>',
					'</h2>',
					'<div class="mt-4 text-lg text-gray-500">' . esc_html__( 'Ac euismod vel sit maecenas id pellentesque eu sed consectetur. Malesuada adipiscing sagittis vel nulla nec.' ) . '</div>',
					'</div>',
					'<div class="mt-12 lg:mt-0 lg:col-span-2">',
					'<div class="space-y-10 sm:space-y-0 sm:grid sm:grid-cols-2 sm:grid-rows-4 sm:grid-flow-col sm:gap-x-6 sm:gap-y-10 lg:gap-x-8">',
					'<div class="relative">',
					'<div>',
					'<div class="material-icons absolute h-6 w-6 text-rose-100">check</div>',
					'<div class="ml-9 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Invite team members' ) . '</div>',
					'</div>',
					'<div class="mt-2 ml-9 text-base text-gray-500">' . esc_html__( 'You can manage phone, email and chat conversations all from a single mailbox.' ) . '</div>',
					'</div>',
					'<div class="relative">',
					'<div>',
					'<div class="material-icons absolute h-6 w-6 text-rose-100">check</div>',
					'<div class="ml-9 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'List view' ) . '</div>',
					'</div>',
					'<div class="mt-2 ml-9 text-base text-gray-500">' . esc_html__( 'You can manage phone, email and chat conversations all from a single mailbox.' ) . '</div>',
					'</div>',
					'<div class="relative">',
					'<div>',
					'<div class="material-icons absolute h-6 w-6 text-rose-100">check</div>',
					'<div class="ml-9 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Keyboard shortcuts' ) . '</div>',
					'</div>',
					'<div class="mt-2 ml-9 text-base text-gray-500">' . esc_html__( 'You can manage phone, email and chat conversations all from a single mailbox.' ) . '</div>',
					'</div>',
					'<div class="relative">',
					'<div>',
					'<div class="material-icons absolute h-6 w-6 text-rose-100">check</div>',
					'<div class="ml-9 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Calendars' ) . '</div>',
					'</div>',
					'<div class="mt-2 ml-9 text-base text-gray-500">' . esc_html__( 'You can manage phone, email and chat conversations all from a single mailbox.' ) . '</div>',
					'</div>',
					'<div class="relative">',
					'<div>',
					'<div class="material-icons absolute h-6 w-6 text-rose-100">check</div>',
					'<div class="ml-9 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Notifications' ) . '</div>',
					'</div>',
					'<div class="mt-2 ml-9 text-base text-gray-500">' . esc_html__( 'Find what you need with advanced filters, bulk actions, and quick views.' ) . '</div>',
					'</div>',
					'<div class="relative">',
					'<div>',
					'<div class="material-icons absolute h-6 w-6 text-rose-100">check</div>',
					'<div class="ml-9 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Boards' ) . '</div>',
					'</div>',
					'<div class="mt-2 ml-9 text-base text-gray-500">' . esc_html__( 'Find what you need with advanced filters, bulk actions, and quick views.' ) . '</div>',
					'</div>',
					'<div class="relative">',
					'<div>',
					'<div class="material-icons absolute h-6 w-6 text-rose-100">check</div>',
					'<div class="ml-9 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Reporting' ) . '</div>',
					'</div>',
					'<div class="mt-2 ml-9 text-base text-gray-500">' . esc_html__( 'Find what you need with advanced filters, bulk actions, and quick views.' ) . '</div>',
					'</div>',
					'<div class="relative">',
					'<div>',
					'<div class="material-icons absolute h-6 w-6 text-rose-100">check</div>',
					'<div class="ml-9 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Mobile app' ) . '</div>',
					'</div>',
					'<div class="mt-2 ml-9 text-base text-gray-500">' . esc_html__( 'Find what you need with advanced filters, bulk actions, and quick views.' ) . '</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Tailwind CSS Features List - 6 Items
	register_block_pattern(
		'alfredknows/features-list-6',
		array(
			'title'         => esc_html__( 'Tailwind CSS Features List - 6 Items', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="bg-white tailwind-css-content-block">',
					'<div class="max-w-7xl mx-auto py-11 px-4 sm:px-6 lg:px-8 lg:grid lg:grid-cols-3 lg:gap-x-8">',
					'<div>',
					'<h2 class="text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl m-0">',
					'<span class="block text-3xl font-extrabold text-gray-900">' . esc_html__( 'All-in-one platform' ) . '</span>',
					'</h2>',
					'<div class="mt-4 text-lg text-gray-500">' . esc_html__( 'Ac euismod vel sit maecenas id pellentesque eu sed consectetur. Malesuada adipiscing sagittis vel nulla nec.' ) . '</div>',
					'</div>',
					'<div class="mt-12 lg:mt-0 lg:col-span-2">',
					'<div class="space-y-10 sm:space-y-0 sm:grid sm:grid-cols-2 sm:grid-rows-3 sm:grid-flow-col sm:gap-x-6 sm:gap-y-10 lg:gap-x-8">',
					'<div class="relative">',
					'<div>',
					'<div class="material-icons absolute h-6 w-6 text-rose-100">check</div>',
					'<div class="ml-9 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Keyboard shortcuts' ) . '</div>',
					'</div>',
					'<div class="mt-2 ml-9 text-base text-gray-500">' . esc_html__( 'You can manage phone, email and chat conversations all from a single mailbox.' ) . '</div>',
					'</div>',
					'<div class="relative">',
					'<div>',
					'<div class="material-icons absolute h-6 w-6 text-rose-100">check</div>',
					'<div class="ml-9 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Calendars' ) . '</div>',
					'</div>',
					'<div class="mt-2 ml-9 text-base text-gray-500">' . esc_html__( 'You can manage phone, email and chat conversations all from a single mailbox.' ) . '</div>',
					'</div>',
					'<div class="relative">',
					'<div>',
					'<div class="material-icons absolute h-6 w-6 text-rose-100">check</div>',
					'<div class="ml-9 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Notifications' ) . '</div>',
					'</div>',
					'<div class="mt-2 ml-9 text-base text-gray-500">' . esc_html__( 'Find what you need with advanced filters, bulk actions, and quick views.' ) . '</div>',
					'</div>',
					'<div class="relative">',
					'<div>',
					'<div class="material-icons absolute h-6 w-6 text-rose-100">check</div>',
					'<div class="ml-9 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Boards' ) . '</div>',
					'</div>',
					'<div class="mt-2 ml-9 text-base text-gray-500">' . esc_html__( 'Find what you need with advanced filters, bulk actions, and quick views.' ) . '</div>',
					'</div>',
					'<div class="relative">',
					'<div>',
					'<div class="material-icons absolute h-6 w-6 text-rose-100">check</div>',
					'<div class="ml-9 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Reporting' ) . '</div>',
					'</div>',
					'<div class="mt-2 ml-9 text-base text-gray-500">' . esc_html__( 'Find what you need with advanced filters, bulk actions, and quick views.' ) . '</div>',
					'</div>',
					'<div class="relative">',
					'<div>',
					'<div class="material-icons absolute h-6 w-6 text-rose-100">check</div>',
					'<div class="ml-9 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Mobile app' ) . '</div>',
					'</div>',
					'<div class="mt-2 ml-9 text-base text-gray-500">' . esc_html__( 'Find what you need with advanced filters, bulk actions, and quick views.' ) . '</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Tailwind CSS Features List - 4 Items
	register_block_pattern(
		'alfredknows/features-list-4',
		array(
			'title'         => esc_html__( 'Tailwind CSS Features List - 4 Items', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="bg-white tailwind-css-content-block">',
					'<div class="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8 lg:grid lg:grid-cols-3 lg:gap-x-8">',
					'<div>',
					'<h2 class="text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl m-0">',
					'<span class="block text-3xl font-extrabold text-gray-900">' . esc_html__( 'All-in-one platform' ) . '</span>',
					'</h2>',
					'<div class="mt-4 text-lg text-gray-500">' . esc_html__( 'Ac euismod vel sit maecenas id pellentesque eu sed consectetur. Malesuada adipiscing sagittis vel nulla nec.' ) . '</div>',
					'</div>',
					'<div class="mt-12 lg:mt-0 lg:col-span-2">',
					'<div class="space-y-10 sm:space-y-0 sm:grid sm:grid-cols-2 sm:grid-rows-2 sm:grid-flow-col sm:gap-x-6 sm:gap-y-10 lg:gap-x-8">',
					'<div class="relative">',
					'<div>',
					'<div class="material-icons absolute h-6 w-6 text-rose-100">check</div>',
					'<div class="ml-9 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Notifications' ) . '</div>',
					'</div>',
					'<div class="mt-2 ml-9 text-base text-gray-500">' . esc_html__( 'Find what you need with advanced filters, bulk actions, and quick views.' ) . '</div>',
					'</div>',
					'<div class="relative">',
					'<div>',
					'<div class="material-icons absolute h-6 w-6 text-rose-100">check</div>',
					'<div class="ml-9 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Boards' ) . '</div>',
					'</div>',
					'<div class="mt-2 ml-9 text-base text-gray-500">' . esc_html__( 'Find what you need with advanced filters, bulk actions, and quick views.' ) . '</div>',
					'</div>',
					'<div class="relative">',
					'<div>',
					'<div class="material-icons absolute h-6 w-6 text-rose-100">check</div>',
					'<div class="ml-9 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Reporting' ) . '</div>',
					'</div>',
					'<div class="mt-2 ml-9 text-base text-gray-500">' . esc_html__( 'Find what you need with advanced filters, bulk actions, and quick views.' ) . '</div>',
					'</div>',
					'<div class="relative">',
					'<div>',
					'<div class="material-icons absolute h-6 w-6 text-rose-100">check</div>',
					'<div class="ml-9 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Mobile app' ) . '</div>',
					'</div>',
					'<div class="mt-2 ml-9 text-base text-gray-500">' . esc_html__( 'Find what you need with advanced filters, bulk actions, and quick views.' ) . '</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Tailwind CSS Product Benefits
	register_block_pattern(
		'alfredknows/product-benefits',
		array(
			'title'         => esc_html__( 'Tailwind CSS Product Benefits', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="py-12 bg-white tailwind-css-content-block">',
					'<div class="max-w-xl mx-auto px-4 sm:px-6 lg:max-w-7xl lg:px-8">',
					'<h2 class="text-center text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">A better way to send money.</h2>',
					'<div class="space-y-10 lg:space-y-0 lg:grid lg:grid-cols-3 lg:gap-8">',
					'<div>',
					'<div>',
					'<div class="flex items-center justify-center h-12 w-12 rounded-md bg-rose-100 text-white">',
					'<div class="material-icons h-6 w-6">language</div>',
					'</div>',
					'<div class="mt-5 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Competitive exchange rates' ) . '</div>',
					'</div>',
					'<div class="mt-2 text-base text-gray-500">' . esc_html__( 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.' ) . '</div>',
					'</div>',
					'<div>',
					'<div>',
					'<div class="flex items-center justify-center h-12 w-12 rounded-md bg-rose-100 text-white">',
					'<div class="material-icons h-6 w-6">attach_money</div>',
					'</div>',
					'<div class="mt-5 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'No hidden fees' ) . '</div>',
					'</div>',
					'<div class="mt-2 text-base text-gray-500">' . esc_html__( 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.' ) . '</div>',
					'</div>',
					'<div>',
					'<div>',
					'<div class="flex items-center justify-center h-12 w-12 rounded-md bg-rose-100 text-white">',
					'<div class="material-icons h-6 w-6">bolt</div>',
					'</div>',
					'<div class="mt-5 text-lg leading-6 font-medium text-gray-900">' . esc_html__( 'Transfers are instant' ) . '</div>',
					'</div>',
					'<div class="mt-2 text-base text-gray-500">' . esc_html__( 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.' ) . '</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Tailwind CSS Spaced Content Block - Text Gray
	register_block_pattern(
		'alfredknows/spaced-content-block',
		array(
			'title'         => esc_html__( 'Tailwind CSS Spaced Content Block - Text Gray', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<!-- wp:group {"className":"tailwind-wp-block relative bg-white py-12"} -->',
					'<div class="wp-block-group tailwind-wp-block relative bg-white py-12"><div class="wp-block-group__inner-container">',
					'<!-- wp:group {"className":"lg:mx-auto lg:max-w-7xl lg:px-8 lg:gap-24 lg:items-start"} -->',
					'<div class="wp-block-group lg:mx-auto lg:max-w-7xl lg:px-8 lg:gap-24 lg:items-start"><div class="wp-block-group__inner-container">',
					'<!-- wp:group {"className":"relative sm:py-16 lg:py-0"} -->',
					'<div class="wp-block-group relative sm:py-16 lg:py-0"><div class="wp-block-group__inner-container">',
					'<!-- wp:heading {"className":"text-3xl text-gray-900 font-extrabold tracking-tight sm:text-4xl text-center"} -->',
					'<h2 class="text-3xl text-gray-900 font-extrabold tracking-tight sm:text-4xl text-center">' . esc_html__( 'Heading', 'alfredknows' ) . '</h2>',
					'<!-- /wp:heading -->',
					'<!-- wp:group {"className":"mt-6 text-gray-500 space-y-6"} -->',
					'<div class="wp-block-group mt-6 text-gray-500 space-y-6"><div class="wp-block-group__inner-container">',
					'<!-- wp:paragraph -->',
					'<p></p>',
					'<!-- /wp:paragraph -->',
					'</div></div>',
					'<!-- /wp:group -->',
					'</div></div>',
					'<!-- /wp:group -->',
					'</div></div>',
					'<!-- /wp:group -->',
					'</div></div>',
					'<!-- /wp:group -->',
				)
			),
		)
	);

	// Tailwind CSS Contact Layout
	register_block_pattern(
		'alfredknows/contact-layout-block',
		array(
			'title'         => esc_html__( 'Tailwind CSS Contact Layout', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="relative bg-white py-12">',
					'<div class="absolute inset-0">',
					'<div class="absolute inset-y-0 left-0 w-1/2 bg-gray-50"></div>',
					'</div>',
					'<div class="relative max-w-7xl mx-auto lg:grid lg:grid-cols-5">',
					'<div class="bg-gray-50 py-16 px-4 sm:px-6 lg:col-span-2 lg:px-8 lg:py-24 xl:pr-12">',
					'<div class="max-w-lg mx-auto">',
					'<h2 class="text-2xl font-extrabold tracking-tight text-gray-900 sm:text-3xl">' . esc_html__( 'Get in touch' ) . '</h2>',
					'<p class="mt-3 text-lg leading-6 text-gray-500">' . esc_html__( 'Nullam risus blandit ac aliquam justo ipsum. Quam mauris volutpat massa dictumst amet. Sapien tortor lacus arcu.' ) . '</p>',
					'<div class="mt-8 text-base text-gray-500">',
					'<div>',
					'<div class="sr-only">' . esc_html__( 'Postal address' ) . '</div>',
					'<div>',
					'<p>' . esc_html__( '742 Evergreen Terrace' ) . '</p>',
					'<p>' . esc_html__( 'Springfield, OR 12345' ) . '</p>',
					'</div>',
					'</div>',
					'<div class="mt-6">',
					'<div class="sr-only">' . esc_html__( 'Phone number' ) . '</div>',
					'<div class="flex">',
					'<span class="material-icons md-18">phone</span>',
					'<span id="contact-phone" class="ml-3">' . esc_html__( '+1 (555) 123-4567' ) . '</span>',
					'</div>',
					'</div>',
					'<div class="mt-3">',
					'<div class="sr-only">' . esc_html__( 'Email' ) . '</div>',
					'<div class="flex">',
					'<span class="material-icons md-18">email</span>',
					'<span id="contact-email" class="ml-3"><a href="mailto:support@example.com">' . esc_html__( 'support@example.com' ) . '</a></span>',
					'</div>',
					'</div>',
					'</div>',
					'<p class="mt-6 text-base text-gray-500">' . esc_html__( 'Looking for careers?  ' ) . '<a href="#" class="font-medium text-gray-700 underline">' . esc_html__( 'View all job openings' ) . '</a>.</p>',
					'</div>',
					'</div>',
					'<div class="bg-white py-16 px-4 sm:px-6 lg:col-span-3 lg:py-24 lg:px-8 xl:pl-12">',
					'<div id="contact-chat" class="max-w-lg mx-auto lg:max-w-none">' . esc_html__( 'Put the contact form here' ) . '</div>',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Tailwind CSS Resources Articles Left
	register_block_pattern(
		'alfredknows/contact-resources-articles-left',
		array(
			'title'         => esc_html__( 'Tailwind CSS Resources Articles - Left', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="my-12 mx-auto max-w-7xl px-4 sm:mt-16 sm:px-6 lg:mt-16">',
					'<div class="lg:grid lg:grid-cols-12 lg:gap-8">',
					'<div class="sm:text-center md:max-w-2xl md:mx-auto lg:col-span-6 lg:text-left">',
					'<h2 class="mt-1 block text-3xl tracking-tight font-extrabold sm:text-4xl xl:text-5xl text-gray-900">' . esc_html__( 'Data to enrich your online business' ) . '</h2>',
					'<p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-xl lg:text-lg xl:text-xl">' . esc_html__( 'Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua ad ad non deserunt sunt.' ) . '</p>',
					'<div class="mt-10 sm:flex sm:justify-center lg:justify-start">',
					'<div class="rounded-md shadow">',
					'<a href="#" class="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-rose-100 hover:bg-rose-200 md:py-4 md:text-lg md:px-10">' . esc_html__( 'Read more here' ) . '</a>',
					'</div>',
					'</div>',
					'</div>',
					'<div class="mt-12 relative sm:max-w-lg sm:mx-auto lg:mt-0 lg:max-w-none lg:mx-0 lg:col-span-6 lg:flex lg:items-center">',
					'<div class="relative ml-auto w-full rounded-lg lg:max-w-md">',
					'<img class="w-full" src="https://images.unsplash.com/photo-1556740758-90de374c12ad?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="">',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Tailwind CSS Resources Articles Right
	register_block_pattern(
		'alfredknows/contact-resources-articles-right',
		array(
			'title'         => esc_html__( 'Tailwind CSS Resources Articles - Right', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="my-12 mx-auto max-w-7xl px-4 sm:px-6">',
					'<div class="lg:grid lg:grid-cols-12 lg:gap-8">',
					'<div class="mt-12 relative sm:max-w-lg sm:mx-auto lg:mt-0 lg:max-w-none lg:mx-0 lg:col-span-6 lg:flex lg:items-center">',
					'<div class="relative mr-auto w-full rounded-lg lg:max-w-md">',
					'<img class="w-full" src="https://images.unsplash.com/photo-1556740758-90de374c12ad?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="">',
					'</div>',
					'</div>',
					'<div class="sm:text-center md:max-w-2xl md:mx-auto lg:col-span-6 lg:text-left">',
					'<h2 class="mt-1 block text-3xl tracking-tight font-extrabold sm:text-4xl xl:text-5xl text-gray-900">' . esc_html__( 'Data to enrich your online business' ) . '</h2>',
					'<p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-xl lg:text-lg xl:text-xl">' . esc_html__( 'Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua ad ad non deserunt sunt.' ) . '</p>',
					'<div class="mt-10 sm:flex sm:justify-center lg:justify-start">',
					'<div class="rounded-md shadow">',
					'<a href="#" class="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-rose-100 hover:bg-rose-200 md:py-4 md:text-lg md:px-10">' . esc_html__( 'Read more here' ) . '</a>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Tailwind CSS Resources Articles Left - No Call to Action
	register_block_pattern(
		'alfredknows/contact-resources-articles-left-no-call',
		array(
			'title'         => esc_html__( 'Tailwind CSS Resources Articles - Left - No Call to Action', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="my-12 mx-auto max-w-7xl px-4 sm:px-6">',
					'<div class="lg:grid lg:grid-cols-12 lg:gap-8">',
					'<div class="sm:text-center md:max-w-2xl md:mx-auto lg:col-span-6 lg:text-left">',
					'<h2 class="mt-1 block text-3xl tracking-tight font-extrabold sm:text-4xl xl:text-5xl text-gray-900">' . esc_html__( 'Data to enrich your online business' ) . '</h2>',
					'<p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-xl lg:text-lg xl:text-xl">' . esc_html__( 'Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua ad ad non deserunt sunt.' ) . '</p>',
					'</div>',
					'<div class="mt-12 relative sm:max-w-lg sm:mx-auto lg:mt-0 lg:max-w-none lg:mx-0 lg:col-span-6 lg:flex lg:items-center">',
					'<div class="relative ml-auto w-full rounded-lg lg:max-w-md">',
					'<img class="w-full" src="https://images.unsplash.com/photo-1556740758-90de374c12ad?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="">',
					'</div>',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	// Tailwind CSS Resources Articles Right
	register_block_pattern(
		'alfredknows/contact-resources-articles-right-no-call',
		array(
			'title'         => esc_html__( 'Tailwind CSS Resources Articles - Right - No Call to Action', 'alfredknows' ),
			'categories'    => array( 'alfredknows' ),
			'viewportWidth' => 1400,
			'content'       => implode(
				'',
				array(
					'<div class="my-12 mx-auto max-w-7xl px-4 sm:px-6">',
					'<div class="lg:grid lg:grid-cols-12 lg:gap-8">',
					'<div class="mt-12 relative sm:max-w-lg sm:mx-auto lg:mt-0 lg:max-w-none lg:mx-0 lg:col-span-6 lg:flex lg:items-center">',
					'<div class="relative mr-auto w-full rounded-lg lg:max-w-md">',
					'<img class="w-full" src="https://images.unsplash.com/photo-1556740758-90de374c12ad?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="">',
					'</div>',
					'</div>',
					'<div class="sm:text-center md:max-w-2xl md:mx-auto lg:col-span-6 lg:text-left">',
					'<h2 class="mt-1 block text-3xl tracking-tight font-extrabold sm:text-4xl xl:text-5xl text-gray-900">' . esc_html__( 'Data to enrich your online business' ) . '</h2>',
					'<p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-xl lg:text-lg xl:text-xl">' . esc_html__( 'Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua ad ad non deserunt sunt.' ) . '</p>',
					'</div>',
					'</div>',
					'</div>',
					'<!-- wp:paragraph -->',
					'<p class="tailwind-css-p-sep">' . esc_html__( '&nbsp;' ) . '</p>',
					'<!-- /wp:paragraph -->',
				)
			),
		)
	);

	
}
